---
- name: Change root password
  hosts: test
  become: yes
  tasks:
    - name: Read password from file
      command: cat password.txt
      register: password_output
      delegate_to: localhost

    - name: Set root password
      user:
        name: root
        password: "{{ password_output.stdout | password_hash('sha512') }}"
